// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: sms-pkg-models.proto

package sms_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmsUuid       []byte `protobuf:"bytes,1,opt,name=sms_uuid,json=smsUuid,proto3" json:"sms_uuid,omitempty"`
	UserUuid      []byte `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CheckPhrase   string `protobuf:"bytes,3,opt,name=check_phrase,json=checkPhrase,proto3" json:"check_phrase,omitempty"`
	IsApproved    bool   `protobuf:"varint,4,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	IsDisapproved bool   `protobuf:"varint,5,opt,name=is_disapproved,json=isDisapproved,proto3" json:"is_disapproved,omitempty"`
}

func (x *Sms) Reset() {
	*x = Sms{}
	mi := &file_sms_pkg_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sms) ProtoMessage() {}

func (x *Sms) ProtoReflect() protoreflect.Message {
	mi := &file_sms_pkg_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sms.ProtoReflect.Descriptor instead.
func (*Sms) Descriptor() ([]byte, []int) {
	return file_sms_pkg_models_proto_rawDescGZIP(), []int{0}
}

func (x *Sms) GetSmsUuid() []byte {
	if x != nil {
		return x.SmsUuid
	}
	return nil
}

func (x *Sms) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *Sms) GetCheckPhrase() string {
	if x != nil {
		return x.CheckPhrase
	}
	return ""
}

func (x *Sms) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *Sms) GetIsDisapproved() bool {
	if x != nil {
		return x.IsDisapproved
	}
	return false
}

var File_sms_pkg_models_proto protoreflect.FileDescriptor

var file_sms_pkg_models_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x6d, 0x73, 0x2d, 0x70, 0x6b, 0x67, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0xa8,
	0x01, 0x0a, 0x03, 0x53, 0x6d, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6d, 0x73, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x6d, 0x73, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x68, 0x72, 0x61, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x61, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x44, 0x69,
	0x73, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x73, 0x6d, 0x73, 0x2d, 0x70, 0x6b, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sms_pkg_models_proto_rawDescOnce sync.Once
	file_sms_pkg_models_proto_rawDescData = file_sms_pkg_models_proto_rawDesc
)

func file_sms_pkg_models_proto_rawDescGZIP() []byte {
	file_sms_pkg_models_proto_rawDescOnce.Do(func() {
		file_sms_pkg_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_sms_pkg_models_proto_rawDescData)
	})
	return file_sms_pkg_models_proto_rawDescData
}

var file_sms_pkg_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sms_pkg_models_proto_goTypes = []any{
	(*Sms)(nil), // 0: models.Sms
}
var file_sms_pkg_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sms_pkg_models_proto_init() }
func file_sms_pkg_models_proto_init() {
	if File_sms_pkg_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sms_pkg_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sms_pkg_models_proto_goTypes,
		DependencyIndexes: file_sms_pkg_models_proto_depIdxs,
		MessageInfos:      file_sms_pkg_models_proto_msgTypes,
	}.Build()
	File_sms_pkg_models_proto = out.File
	file_sms_pkg_models_proto_rawDesc = nil
	file_sms_pkg_models_proto_goTypes = nil
	file_sms_pkg_models_proto_depIdxs = nil
}
