// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: sms-pkg-models.proto

package sms_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SmsUuid       []byte                 `protobuf:"bytes,1,opt,name=sms_uuid,json=smsUuid,proto3" json:"sms_uuid,omitempty"`
	UserUuid      []byte                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CheckPhrase   string                 `protobuf:"bytes,3,opt,name=check_phrase,json=checkPhrase,proto3" json:"check_phrase,omitempty"`
	IsApproved    bool                   `protobuf:"varint,4,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	IsDisapproved bool                   `protobuf:"varint,5,opt,name=is_disapproved,json=isDisapproved,proto3" json:"is_disapproved,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sms) Reset() {
	*x = Sms{}
	mi := &file_sms_pkg_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sms) ProtoMessage() {}

func (x *Sms) ProtoReflect() protoreflect.Message {
	mi := &file_sms_pkg_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sms.ProtoReflect.Descriptor instead.
func (*Sms) Descriptor() ([]byte, []int) {
	return file_sms_pkg_models_proto_rawDescGZIP(), []int{0}
}

func (x *Sms) GetSmsUuid() []byte {
	if x != nil {
		return x.SmsUuid
	}
	return nil
}

func (x *Sms) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *Sms) GetCheckPhrase() string {
	if x != nil {
		return x.CheckPhrase
	}
	return ""
}

func (x *Sms) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *Sms) GetIsDisapproved() bool {
	if x != nil {
		return x.IsDisapproved
	}
	return false
}

func (x *Sms) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

var File_sms_pkg_models_proto protoreflect.FileDescriptor

const file_sms_pkg_models_proto_rawDesc = "" +
	"\n" +
	"\x14sms-pkg-models.proto\x12\x06models\"\xbe\x01\n" +
	"\x03Sms\x12\x19\n" +
	"\bsms_uuid\x18\x01 \x01(\fR\asmsUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\fR\buserUuid\x12!\n" +
	"\fcheck_phrase\x18\x03 \x01(\tR\vcheckPhrase\x12\x1f\n" +
	"\vis_approved\x18\x04 \x01(\bR\n" +
	"isApproved\x12%\n" +
	"\x0eis_disapproved\x18\x05 \x01(\bR\risDisapproved\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phoneB\x13Z\x11protocols/sms-pkgb\x06proto3"

var (
	file_sms_pkg_models_proto_rawDescOnce sync.Once
	file_sms_pkg_models_proto_rawDescData []byte
)

func file_sms_pkg_models_proto_rawDescGZIP() []byte {
	file_sms_pkg_models_proto_rawDescOnce.Do(func() {
		file_sms_pkg_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sms_pkg_models_proto_rawDesc), len(file_sms_pkg_models_proto_rawDesc)))
	})
	return file_sms_pkg_models_proto_rawDescData
}

var file_sms_pkg_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sms_pkg_models_proto_goTypes = []any{
	(*Sms)(nil), // 0: models.Sms
}
var file_sms_pkg_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sms_pkg_models_proto_init() }
func file_sms_pkg_models_proto_init() {
	if File_sms_pkg_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sms_pkg_models_proto_rawDesc), len(file_sms_pkg_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sms_pkg_models_proto_goTypes,
		DependencyIndexes: file_sms_pkg_models_proto_depIdxs,
		MessageInfos:      file_sms_pkg_models_proto_msgTypes,
	}.Build()
	File_sms_pkg_models_proto = out.File
	file_sms_pkg_models_proto_goTypes = nil
	file_sms_pkg_models_proto_depIdxs = nil
}
